title:            "My Thinkspace"
tagline:          Strong opinions, weakly held
description:      Strong opinions, weakly held
baseurl: "" 
url: "https://opsbug.com"

# Owner/author information
owner:
  name:           Vikram Dhillon
  bio:            "Soon to be on first name basis with the world"
  email:          dhillonv10@gmail.com
  twitter:        opsbug
  disqus:         opsbug

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

## How to make an external link in the top nav-bar
#  - title: Cole Who?
#    url: http://coletownsend.com
#    external: true
#

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: rouge
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed

jekyll-mentions:
  base_url: https://twitter.com  

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]