# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            OpsBug
tagline:          'Strong Opinions, Weakly Held.'
description:      'Tech Renaissance.'
url:              https://www.opsbug.com/
baseurl:          ''

# Travis will install Bundler dependencies in ./vendor, so we need to exclude it
# otherwise Jekyll will try to build it (and fail)
exclude:          [vendor]

author:
  name:           'Vikram Dhillon'
  url:            https://www.opsbug.com/
# Thanks to @mdo for the original theme
# author:
#   name:           'Mark Otto'
#   url:            https://twitter.com/mdo



# Algolia
gems:
  - algoliasearch-jekyll
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed

jekyll-mentions:
  base_url: https://twitter.com

algolia:
  application_id: 'FWV1YODXHM'
  index_name: 'jekyll'
  read_only_api_key: '8393e45dbb98be1ddf66f9d767ef681e'
  ALGOLIA_API_KEY: 'ac30b748b98caed76f2affc57a062b4d'
  excluded_files:
    - 404.html
    - index.html

