title: Vikram D.
description: Writer, medical student, blockchain developer

lang: en-US
branch: master

# Pages to include in header navigation
nav_pages:
  - index.html
  - about.md

footer_pages:
  - fine-print.md

# Disqus login information, for comments
disqus:
  shortname: opsbug

# Google Analytics tracking id
ga_username: UA-xxxxxxxx-x

# Links to include on the contact page
contact_links:
  - name: Twitter
    url: https://twitter.com/opsbug
    icon: twitter

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      comments: false

plugins:
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-mentions  

exclude:
  - vendor/bundle
  - node_modules
  - js
  - sass

theme: null

jekyll-mentions:
  base_url: https://twitter.com   

remote_theme: benbalter/retlab
